// Imported by subpath, not the barrel — the barrel pulls node:path/sharp
// into the browser bundle (see dslToSearch.ts). `dslAtom` moved into core
// (K83) so this file and the visual query builder's serializer share ONE
// atom formatter.
import { conditionsToDsl, queryToConditions } from "@loctt/core/query/builderTree.js";
import { dslAtom } from "@loctt/core/query/serialize.js";

import type { ListSearch } from "../router/listSearch.ts";
import { buildConditionsFromSearch } from "./buildConditions.ts";

// Re-exported so existing importers (and buildDsl.test.ts) keep their
// `./buildDsl` entry point after the atom formatter moved into core.
export { dslAtom };

/**
 * Builds a LocTT query-DSL string from the active list filters, for
 * saving the current view (M1.3 "Save as view").
 *
 * STRUCTURE-FIRST (Stage 2): this is now a thin wrapper over
 * {@link buildConditionsFromSearch} — it builds the structured
 * {@link BuilderTree} and serializes it with core's spacing-only
 * serializer ({@link conditionsToDsl}). The string is therefore ALWAYS a
 * faithful serialization of the same structure a "Save as view" stores,
 * so the two can never disagree, and the DSL is generated by ONE code
 * path (core's serializer) rather than re-implemented here.
 *
 * Consequences of the switch, both deliberate:
 * - A multi-select facet always uses membership (`status in (A)`), never
 *   the old count-based `= A` downgrade (Ken's ruling).
 * - The free-text `q` is parsed and spliced structurally, so it is
 *   re-emitted by the serializer (no blanket `(...)` wrap); DSL
 *   precedence, not a defensive paren, keeps its meaning.
 */
export function buildDslFromSearch(search: Partial<ListSearch>): string {
  return conditionsToDsl(buildConditionsFromSearch(search, queryToConditions));
}
